### PR TITLE
Add Managed Identity support for DurableTask.ServiceBus

### PR DESCRIPTION
**Pull request by AlexKuriatnyk**
Adding possibility to use Managed Identity or other type of identity authentication with DurableTask.ServiceBus

Resolves https://github.com/Azure/durabletask/issues/414

### CODE REVIEW

**Comment by cgillum** [comment]
It looks like there's something wrong with our CI build right now. We'll check it out and re-run this PR once we've sorted things out.

**Comment by cgillum** [comment]
Hi @AlexKuriatnyk can you merge the latest from master and update your PR? That should resolve the problem with the CI.

**Comment by AlexKuriatnyk** [comment]
@cgillum , I have merged it with the latest master and updated PR.

**Comment by cgillum** [comment]
Finally got the CI issue resolved. 😀 Merging this now. We'll include it in the next publish to nuget.org.

**Comment by AlexKuriatnyk** [comment]
@cgillum , when are you planning to publish a new version? We are looking forward to it :)

**Comment by cgillum** [comment]
@AlexKuriatnyk I'll try to get it published sometime in the next two weeks.

**Pull request merged**
