### PR TITLE
Reset NumTimeoutsHit periodically

### LINKED ISSUE #676: NumTimeoutsHit is never reset
The `NumTimeoutsHit` field in `TimeoutHandler` is never reset. This means that if you happen to have a sporadic timeout every now-and-then, the count keeps increasing, resulting in the process being killed.
While this might work for short-lived processes, this is impacting long-running processes, which might have sporadic storage timeouts, even if those are spread over a very long period.

A workaround could be adding a timestamp to "remember" when the last timeout happened, and reset it if enough time happened, or using some form of trickling-bucket algorithm.

### PR DESCRIPTION
**Pull request by saguiitay**
This PR resolves #676.

This PR resets the `NumTimeoutsHit` count in `TimeoutHandler`, to avoid long-running processes from being impacted by sporadic timeouts.

### CODE REVIEW

**Comment by saguiitay** [comment]
@amdeel could you please take a look? This is a critical issue to ADX

**Comment by saguiitay** [comment]
@cgillum, @amdeel could you please re-run the pipeline

**Review by cgillum — APPROVED** [review]
Re-run of the CI is green. Thanks for this contribution! It will be included automatically in our next planned release of DurableTask.AzureStorage.

**Pull request merged**
