### PR TITLE
Changing ExecutionContext tags from IReadonlyDictionary to IDictionary

### PR DESCRIPTION
**Pull request by RamjotSingh**

### CODE REVIEW

**Comment by jviau** [comment]
Can you add a unit test using `DataContractSerializer` to serialize/deserialize this type?

**Comment by RamjotSingh** [comment]
@jviau Added a unit test for data contract serialization. Please review.

**Review by jviau — APPROVED** [review]

**Comment by jviau** [comment]
@RamjotSingh, One last change needed: can you rev the package version to 2.12.1? We can delist 2.12 from NuGet after this is published.

**Review by cgillum — APPROVED** [review]

**Pull request merged**
