### PR TITLE
Rename local variable taskHub to avoid confusion

### PR DESCRIPTION
**Pull request by BilalAlam**

### CODE REVIEW

**Comment by davidmrdavid** [comment]
I had to triple check for a second that this was actually you, @BilalAlam :-P

**Review by davidmrdavid — APPROVED** [review]
LGTM after CI goes green

**Comment by cgillum** [comment]
Better run this through the CI to make sure it doesn't mess everything up...

/azp run

**Comment by BilalAlam** [comment]
> I had to triple check for a second that this was actually you, @BilalAlam :-P

Do at least one (slightly) useful thing during my sabbatical...  Check.  :-)

**Review by cgillum — APPROVED** [review]
Looks like our CI excludes the samples directory, so we're good to go with this.

Congrats on your first DTFx contribution! :)

**Pull request merged**
