### PR TITLE
first step towards .net core 2.0

### PR DESCRIPTION
**Pull request by ElanHasson**
This PR is not yet meant for merging, it's add to the discussion at #96

### CODE REVIEW

**Comment by mnadeau2** [comment]
is there any eta for support of Net core 2.0 ? this is impacting us.

**Comment by mnadeau2** [comment]
any news ?

**Comment by christianh25** [comment]
any ETA? my newest project is core 2.0 and this would really make my life easier

**Comment by simonporter** [comment]
Closing in favor of #203 which we are working to merge. 
Thanks for the effort to get this initial work done.

**Pull request closed without merging**
