### PR TITLE
SQL Server provider for IOrchestrationServiceInstanceStore

### PR DESCRIPTION
**Pull request by cbrianball**
This PR provides an implementation of `IOrchestrationServiceInstnaceStore` that will persist Orchestartion State and Work Item State data to SQL Server.

A few notes:
- Currently there is no support for JumpStartEntities
- The "unit tests" are really integration tests that use a SQL Server docker image
  - I could have mocked the database, but there is minimal logic in the code, it is mostly a data access layer, so I felt it was most important to verify that the data is persisted/read correctly.
- The SQL is hard-coded in the library (I do use parameterized queries). I did this because I wanted to minimize the number of dependencies the library needed
- The library uses `System.Data.DbConnection` instead of `System.Data.SqlClient.SqlConnection` because soon MSFT will release `Microsoft.Data.SqlClient`, which inherits from `System.Data.DbConnection` as well, so this is a way of allowing consumers to use either SQL Client library
- The library obtains a `DbConnection` instance via a delegate that is provided; I had the delegate return a `Task<DbConnection>` so that it would be easier for consumers that need to first acquire an Access Token from AAD, for consumers that don't need to, they can return `Task.FromResult<...>(...)`

Here's a quick example of how to use the SQL Server instance store with the Azure Storage Orchestration:
````
var storeSettings = new SqlServerInstanceStoreSettings
            {
                GetDatabaseConnection = () => Task.FromResult<DbConnection>(new SqlConnection("...")),
                HubName = "Workflows",
                SchemaName = "durabletask"
            };
var instanceStore = new SqlServerInstanceStore(storeSettings);

var orchestrationSettings = new AzureStorageOrchestrationServiceSettings
            {
                StorageConnectionString = "...",
                TaskHubName = "Workflows",
            };
var orchestration = new AzureStorageOrchestrationService(orchestrationSettings, instanceStore);
````

### CODE REVIEW

**Comment by cbrianball** [comment]
@simonporter Is the team interested in this pull request? This type of functionality was specifically requested in the repo's README file (the second bullet point in the TODO list).

**Comment by ElanHasson** [comment]
We're interested in the SQL provider. We're looking to run in our private cloud and this would be extremely helpful. If all goes well, we'll need a RabbitMQ provider also.

**Comment by cbrianball** [comment]
@simonporter @cgillum I submitted this PR over 7 weeks ago and there has been very little activity. Are there any plans to review this and potentially accept it? I think there are a lot of people who would like to see a provider for SQL Server implemented.

**Comment by ElanHasson** [comment]
@cbrianball,

Would you mind reaching out to me at elan_hasson (at) ultimatesoftware (dot) com.

I'd like to chat about this PR and better understand it. I'm going to most likely be putting together one for mongo soon 

Thanks

**Comment by cbrianball** [comment]
@ElanHasson I'll shoot you an email in the next day or so.

**Comment by cbrianball** [comment]
@cgillum I will update the code either today or tomorrow to remove the password and provide details in the resulting exception if a weak password is provided that will aid the developer in troubleshooting the error.

I can publish this as a NuGet package under my own account, but I was hoping it would get published by the maintainers of the DurableTask framework (I apologize for not asking for that up front).

**Comment by cbrianball** [comment]
@cgillum I updated the Test project to no longer have a hard-coded password and added helpful exception messages.

I also merged in recent changes from the master branch to ensure there are currently no conflicts in this PR.

**Comment by ElanHasson** [comment]
I am hoping the this new package would be published as an official Microsoft package as it would help with adoption and provide some guarantees around the contents of the package.

This may also make more sense as the code would live in this repo (I am assuming, as the PR is here ☺).

**Comment by Radytz** [comment]
Is this PR still active? i would like to use this as a base to try and create a similar implementation but with Orleans instead of SQL server.

**Comment by cbrianball** [comment]
@Radytz As far as I'm aware, it's still open. It's up to the maintainers at this point to accept or reject it.

**Comment by cgillum** [comment]
Sorry for the delay on this and thank you for removing the hard-coded password. It's really cool to see extensions like this. I'll go ahead and make the executive decision to accept this. :)

**Pull request merged**
