### PR TITLE
Make Storage timeouts handling configurable

### PR DESCRIPTION
**Pull request by saguiitay**
This PR allows users to configure the various settings of Timeout handling:

* MaxNumberOfTimeoutsBeforeRecycle
* StorageRequestsTimeout
* StorageRequestsTimeoutCooldown

This allows having more permissive handling in noise scenarios (e.g. when the Storage Account is shared with other scenarios), or unstable scenarios (e.g. when the Storage Account experiences longer delays).

### CODE REVIEW

**Comment by saguiitay** [comment]
@cgillum Gentle ping

**Review by cgillum — APPROVED** [review]
LGTM! Hopefully we can deprecate these soon since the storage SDK update is underway.

**Comment by sojwil** [comment]
Excellent! Will be waiting for the release. Thanks!

**Pull request merged**
